service: chinmaya-janata-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  environment:
    USERS_TABLE: ChinmayaJanata-Users
    CENTERS_TABLE: ChinmayaJanata-Centers
    EVENTS_TABLE: ChinmayaJanata-Events
    ADMIN_NAME: Brahman
    NODE_ENV: development
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:us-east-1:*:table/ChinmayaJanata-Users
            - arn:aws:dynamodb:us-east-1:*:table/ChinmayaJanata-Centers
            - arn:aws:dynamodb:us-east-1:*:table/ChinmayaJanata-Events
            - arn:aws:dynamodb:us-east-1:*:table/ChinmayaJanata-Events/index/*

resources:
  Resources:
    UsersDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ChinmayaJanata-Users
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

    CentersDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ChinmayaJanata-Centers
        AttributeDefinitions:
          - AttributeName: centerID
            AttributeType: N
        KeySchema:
          - AttributeName: centerID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

    EventsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ChinmayaJanata-Events
        AttributeDefinitions:
          - AttributeName: eventID
            AttributeType: S
          - AttributeName: centerID
            AttributeType: N
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: eventID
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: centerID-index
            KeySchema:
              - AttributeName: centerID
                KeyType: HASH
              - AttributeName: date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true